name: ItemGenerator
main: de.cruelambition.itemgenerator.ItemGenerator
version: '0.1.1'
api-version: '1.20'
author: CruelAmbition / Rae
description: this awesome generation mini game :)

commands:
  fly:
    description: toggle flight mode. No game mode change required!
    aliases:
      - Flight
  info:
    description: Get basic plugin and user Info
  checkmessage:
    description: Check if a message is set / which messages are unset
  playtime:
    description: View your current play time
  language:
    description: set your ingame language
  invsee:
    description: view another players inventory
  generatorfrequencies:
    description: Adjust the generator settings in game!
  chat:
    description: Customize your chat experience
  backpack:
    description: Expand your inventory
  arms:
    description: Add arms to nearby armorstands
  get:
    description: Get custom Items by this very plugin
  spawn:
    description: Go to the spawn