name: ItemGenerator
main: de.cruelambition.itemgenerator.ItemGenerator
version: '0.0.1'
api-version: '1.20'
author: CruelAmbition
description: oki doke

commands:
  fly:
    description: toggle flight mode. No game mode change required!
    aliases:
      - Flight
  info:
    description: Get basic plugin and user Info
