name: ItemGenerator
main: de.cruelambition.Main
version: '0.0.1'
api-version: '1.20'
author: CruelAmbition
description: oki doki

commands:
  fly:
    description: toggle flight mode. No game mode change required!
    aliases:
      - Flight
  info:
    description: Get basic plugin and user Info
  checkmessage:
    description: Check if a message is set / which messages are unset