name: ItemGenerator
main: de.cruelambition.itemgenerator.ItemGenerator
version: '0.1.0'
api-version: 1.19
authors: [ CruelAmbition ]
description: okay

commands:
  Fly:
    description: toggle flight mode - no gamemode change required!
    aliases:
      - Flight
    usage: /Fly <Player>
    permission: ItemGenerator.Fly.Self

  Info:
    description: Get basic Plugin / User Info
